name: audio_player
description: Reusable audio player module with background playback, notifications, and lock screen controls.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  cupertino_native: ^0.1.1
  just_audio: ^0.9.36
  audio_service: ^0.18.11
  rxdart: ^0.28.0
  lottie: ^3.1.0
  modal_bottom_sheet: ^3.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  freezed: ^2.4.7
  json_serializable: ^6.1.1
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
